//
//  WordpackClothers.swift
//  AliasApp
//
//  Created by Илья Желтиков on 18.05.2023.
//

import Foundation

extension WordPackManager {
    
    func getClothesWords() -> [Word] {
        return [
            Word(english: "Shirt", russian: "Рубашка"),
            Word(english: "Blouse", russian: "Блузка"),
            Word(english: "T-Shirt", russian: "Футболка"),
            Word(english: "Sweater", russian: "Свитер"),
            Word(english: "Jacket", russian: "Куртка"),
            Word(english: "Coat", russian: "Пальто"),
            Word(english: "Dress", russian: "Платье"),
            Word(english: "Skirt", russian: "Юбка"),
            Word(english: "Jeans", russian: "Джинсы"),
            Word(english: "Trousers", russian: "Брюки"),
            Word(english: "Shorts", russian: "Шорты"),
            Word(english: "Leggings", russian: "Леггинсы"),
            Word(english: "Suit", russian: "Костюм"),
            Word(english: "Vest", russian: "Жилет"),
            Word(english: "Socks", russian: "Носки"),
            Word(english: "Stockings", russian: "Чулки"),
            Word(english: "Tights", russian: "Колготки"),
            Word(english: "Shoes", russian: "Обувь"),
            Word(english: "Boots", russian: "Ботинки"),
            Word(english: "Sneakers", russian: "Кроссовки"),
            Word(english: "Sandals", russian: "Сандалии"),
            Word(english: "Slippers", russian: "Тапочки"),
            Word(english: "Hat", russian: "Шапка"),
            Word(english: "Cap", russian: "Кепка"),
            Word(english: "Beanie", russian: "Шапочка"),
            Word(english: "Scarf", russian: "Шарф"),
            Word(english: "Gloves", russian: "Перчатки"),
            Word(english: "Mittens", russian: "Варежки"),
            Word(english: "Belt", russian: "Пояс"),
            Word(english: "Tie", russian: "Галстук"),
            Word(english: "Bowtie", russian: "Бабочка"),
            Word(english: "Handbag", russian: "Сумка"),
            Word(english: "Backpack", russian: "Рюкзак"),
            Word(english: "Wallet", russian: "Кошелек"),
            Word(english: "Purse", russian: "Кошелек"),
            Word(english: "Jewelry", russian: "Украшения"),
            Word(english: "Necklace", russian: "Ожерелье"),
            Word(english: "Bracelet", russian: "Браслет"),
            Word(english: "Earrings", russian: "Серьги"),
            Word(english: "Ring", russian: "Кольцо"),
            Word(english: "Watch", russian: "Часы"),
            Word(english: "Sunglasses", russian: "Солнцезащитные очки"),
            Word(english: "Umbrella", russian: "Зонт"),
            Word(english: "Tie", russian: "Галстук"),
            Word(english: "Bathrobe", russian: "Халат"),
            Word(english: "Pyjamas", russian: "Пижама"),
            Word(english: "Swimsuit", russian: "Купальник"),
            Word(english: "Bikini", russian: "Бикини"),
            Word(english: "Underwear", russian: "Нижнее белье"),
            Word(english: "Bra", russian: "Бюстгальтер"),
            Word(english: "Panties", russian: "Трусики"),
            Word(english: "Boxers", russian: "Трусы"),
            Word(english: "Suspenders", russian: "Подтяжки"),
            Word(english: "Apron", russian: "Фартук"),
            Word(english: "Overall", russian: "Комбинезон"),
            Word(english: "Uniform", russian: "Униформа"),
            Word(english: "Cloak", russian: "Плащ"),
            Word(english: "Cloth", russian: "Ткань"),
            Word(english: "Fabric", russian: "Ткань"),
            Word(english: "Pattern", russian: "Узор"),
            Word(english: "Button", russian: "Пуговица"),
            Word(english: "Zipper", russian: "Застежка-молния"),
            Word(english: "Pocket", russian: "Карман"),
            Word(english: "Lace", russian: "Кружево"),
            Word(english: "Seam", russian: "Шов"),
            Word(english: "Stitch", russian: "Строчка"),
            Word(english: "Iron", russian: "Утюг"),
            Word(english: "Laundry", russian: "Прачечная"),
            Word(english: "Washing", russian: "Стирка"),
            Word(english: "Drying", russian: "Сушка"),
            Word(english: "Fold", russian: "Складывать"),
            Word(english: "Hang", russian: "Вешать"),
            Word(english: "Wardrobe", russian: "Шкаф для одежды"),
            Word(english: "Fashion", russian: "Мода"),
            Word(english: "Style", russian: "Стиль"),
            Word(english: "Designer", russian: "Дизайнер"),
            Word(english: "Catwalk", russian: "Катwalk"),
            Word(english: "Model", russian: "Модель"),
            Word(english: "Runway", russian: "Подиум"),
            Word(english: "Clothing", russian: "Одежда"),
            Word(english: "Fashionable", russian: "Модный"),
            Word(english: "Trendy", russian: "Стильный"),
            Word(english: "Comfortable", russian: "Удобный"),
            Word(english: "Stylish", russian: "Стильный"),
            Word(english: "Chic", russian: "Шикарный"),
            Word(english: "Casual", russian: "Повседневный"),
            Word(english: "Formal", russian: "Официальный")
        ]
    }
}
