//
//  WordpackGeneral.swift
//  AliasApp
//
//  Created by Илья Желтиков on 18.05.2023.
//

import Foundation

extension WordPackManager {
    func getGeneralWords() -> [Word] {
        return [
        Word(english: "Time", russian: "Время"),
        Word(english: "Day", russian: "День"),
        Word(english: "Night", russian: "Ночь"),
        Word(english: "Morning", russian: "Утро"),
        Word(english: "Afternoon", russian: "День"),
        Word(english: "Evening", russian: "Вечер"),
        Word(english: "Week", russian: "Неделя"),
        Word(english: "Month", russian: "Месяц"),
        Word(english: "Year", russian: "Год"),
        Word(english: "Today", russian: "Сегодня"),
        Word(english: "Yesterday", russian: "Вчера"),
        Word(english: "Tomorrow", russian: "Завтра"),
        Word(english: "Weekend", russian: "Выходные"),
        Word(english: "Holiday", russian: "Праздник"),
        Word(english: "Birthday", russian: "День рождения"),
        Word(english: "Anniversary", russian: "Годовщина"),
        Word(english: "Party", russian: "Вечеринка"),
        Word(english: "Celebration", russian: "Празднование"),
        Word(english: "Meeting", russian: "Встреча"),
        Word(english: "Appointment", russian: "Назначение"),
        Word(english: "Conversation", russian: "Разговор"),
        Word(english: "Discussion", russian: "Обсуждение"),
        Word(english: "Agreement", russian: "Соглашение"),
        Word(english: "Disagreement", russian: "Несогласие"),
        Word(english: "Decision", russian: "Решение"),
        Word(english: "Problem", russian: "Проблема"),
        Word(english: "Solution", russian: "Решение"),
        Word(english: "Question", russian: "Вопрос"),
        Word(english: "Answer", russian: "Ответ"),
        Word(english: "Knowledge", russian: "Знание"),
        Word(english: "Learning", russian: "Обучение"),
        Word(english: "Education", russian: "Образование"),
        Word(english: "School", russian: "Школа"),
        Word(english: "University", russian: "Университет"),
        Word(english: "Classroom", russian: "Класс"),
        Word(english: "Teacher", russian: "Учитель"),
        Word(english: "Student", russian: "Студент"),
        Word(english: "Lesson", russian: "Урок"),
        Word(english: "Exam", russian: "Экзамен"),
        Word(english: "Homework", russian: "Домашнее задание"),
        Word(english: "Project", russian: "Проект"),
        Word(english: "Task", russian: "Задание"),
        Word(english: "Work", russian: "Работа"),
        Word(english: "Job", russian: "Работа"),
        Word(english: "Career", russian: "Карьера"),
        Word(english: "Success", russian: "Успех"),
        Word(english: "Failure", russian: "Провал"),
        Word(english: "Goal", russian: "Цель"),
        Word(english: "Dream", russian: "Мечта"),
        Word(english: "Ambition", russian: "Амбиция"),
        Word(english: "Challenge", russian: "Испытание"),
        Word(english: "Opportunity", russian: "Возможность"),
        Word(english: "Experience", russian: "Опыт"),
        Word(english: "Skill", russian: "Навык"),
        Word(english: "Talent", russian: "Талант"),
        Word(english: "Creativity", russian: "Творчество"),
        Word(english: "Imagination", russian: "Воображение"),
        Word(english: "Inspiration", russian: "Вдохновение"),
        Word(english: "Motivation", russian: "Мотивация"),
        Word(english: "Effort", russian: "Усилие"),
        Word(english: "Progress", russian: "Прогресс"),
        Word(english: "Change", russian: "Изменение"),
        Word(english: "Development", russian: "Развитие"),
        Word(english: "Innovation", russian: "Инновация"),
        Word(english: "Improvement", russian: "Улучшение"),
        Word(english: "Adaptation", russian: "Адаптация"),
        Word(english: "Decision", russian: "Решение"),
        Word(english: "Risk", russian: "Риск"),
        Word(english: "Chance", russian: "Шанс"),
        Word(english: "Luck", russian: "Удача"),
        Word(english: "Happiness", russian: "Счастье"),
        Word(english: "Sadness", russian: "Грусть"),
        Word(english: "Emotion", russian: "Эмоция"),
        Word(english: "Feeling", russian: "Чувство"),
        Word(english: "Love", russian: "Любовь"),
        Word(english: "Friendship", russian: "Дружба"),
        Word(english: "Family", russian: "Семья"),
        Word(english: "Relationship", russian: "Отношение"),
        Word(english: "Marriage", russian: "Брак"),
        Word(english: "Divorce", russian: "Развод"),
        Word(english: "Parent", russian: "Родитель"),
        Word(english: "Child", russian: "Ребенок"),
        Word(english: "Brother", russian: "Брат"),
        Word(english: "Sister", russian: "Сестра"),
        Word(english: "Friend", russian: "Друг"),
        Word(english: "Colleague", russian: "Коллега"),
        Word(english: "Neighbor", russian: "Сосед"),
        Word(english: "Community", russian: "Сообщество"),
        Word(english: "Society", russian: "Общество"),
        Word(english: "Culture", russian: "Культура"),
        Word(english: "Tradition", russian: "Традиция"),
        Word(english: "Custom", russian: "Обычай"),
        Word(english: "Etiquette", russian: "Этикет"),
        Word(english: "Value", russian: "Ценность"),
        Word(english: "Belief", russian: "Вера"),
        Word(english: "Morality", russian: "Мораль"),
        Word(english: "Ethics", russian: "Этика"),
        Word(english: "Respect", russian: "Уважение"),
        Word(english: "Equality", russian: "Равенство"),
        Word(english: "Justice", russian: "Справедливость"),
        Word(english: "Freedom", russian: "Свобода"),
        Word(english: "Peace", russian: "Мир"),
        Word(english: "War", russian: "Война"),
        Word(english: "Conflict", russian: "Конфликт"),
        Word(english: "Cooperation", russian: "Сотрудничество"),
        Word(english: "Communication", russian: "Общение"),
        Word(english: "Trust", russian: "Доверие"),
        Word(english: "Betrayal", russian: "Предательство"),
        Word(english: "Forgiveness", russian: "Прощение"),
        Word(english: "Gratitude", russian: "Благодарность")
        ]
    }
}
